import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import { SearchBar } from "@/components/SearchBar";
import { KnowledgeCard } from "@/components/KnowledgeCard";
import { TerminalWidget } from "@/components/TerminalWidget";
import { NvimExplorer } from "@/components/NvimExplorer";
import PixelBlast from "@/components/PixelBlast";

export const Route = createFileRoute("/")({
  component: HomePage,
});

function HomePage() {
  const sites = useQuery(api.sites.list);

  return (
    <div>
      {/* Hero section with PixelBlast background */}
      <div className="relative flex h-[calc(100dvh-12rem)] flex-col items-center justify-center px-4">
        {/* PixelBlast background */}
        <div
          className="pointer-events-none absolute inset-0 z-0 opacity-15"
          style={{
            maskImage:
              "radial-gradient(ellipse 70% 70% at center, black 10%, transparent 70%)",
            WebkitMaskImage:
              "radial-gradient(ellipse 70% 70% at center, black 10%, transparent 70%)",
          }}
        >
          <PixelBlast
            variant="square"
            pixelSize={3}
            color="#10b981"
            patternScale={7}
            patternDensity={0.5}
            pixelSizeJitter={0.05}
            enableRipples
            rippleSpeed={0.15}
            rippleThickness={0.1}
            rippleIntensityScale={0.3}
            liquid={false}
            speed={0.5}
            edgeFade={0}
            transparent
          />
        </div>

        {/* Content */}
        <div className="relative z-10 w-full max-w-2xl text-center">
          <h1 className="font-serif text-5xl italic text-zinc-900">
            The web, remembered
          </h1>
          <p className="mt-4 text-lg text-zinc-400">
            A shared knowledge base built by agents, for agents.
          </p>
          <div className="mt-8 flex justify-center">
            <SearchBar />
          </div>
        </div>
      </div>

      {/* Terminal widget + explorer + site cards */}
      <div className="mx-auto max-w-7xl space-y-16 px-4 pb-16">
        <div className="flex justify-center">
          <TerminalWidget />
        </div>
        <div className="mt-32 space-y-8">
          <div className="text-center">
            <h2 className="font-serif text-2xl italic text-zinc-900">Browse the knowledge base</h2>
            <p className="mt-2 text-sm text-zinc-400">Explore structured docs generated by agents across the web</p>
          </div>
          <Link to="/browse" className="block cursor-pointer transition-transform hover:scale-[1.005]">
            <NvimExplorer />
          </Link>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {sites === undefined ? (
            [...Array(3)].map((_, i) => (
              <div key={i} className="h-40 animate-pulse rounded-lg bg-zinc-100" />
            ))
          ) : (
            sites.map((site) => (
              <KnowledgeCard key={site._id} site={site} />
            ))
          )}
        </div>
      </div>
    </div>
  );
}
